# Generated by Django 2.0.1 on 2018-01-28 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_des', models.CharField(max_length=200)),
                ('long_des', models.TextField()),
                ('solved', models.CharField(max_length=10)),
                ('passing_line', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('category', models.ManyToManyField(to='lb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.TextField()),
                ('sub_date', models.DateTimeField(verbose_name='date published')),
                ('envir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.Environment')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('reg_time', models.DateTimeField()),
                ('department', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lb.User'),
        ),
    ]
