# Generated by Django 2.0.1 on 2018-01-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='join_nb',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='environment',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sub_date',
            field=models.DateTimeField(),
        ),
    ]
